[build]
command = "npm run build"
[build.upload]
format = "modules"
main = "./src/main.jsx"
rules = [
  { type = "Data", globs = ["**/*.svg"] }
]
pages_build_output_dir = "dist"
compatibility_date = "2024-10-30"
directory = "dist"